// test t5_1_success_rotate_key() {
//   let redeemer =
//     DexRotateKey {
//       new_operation_key: mock_stop_key(),
//       new_stop_key: mock_pub_key_hash(3),
//     }
//   let input_utxo = mock_utxo_ref(0, 0)

//   let tx = mock_rotate_test_case(base_rotate_test_case())

//   dex_oracle.dex_oracle.spend(
//     Some(mock_dex_oracle_datum()),
//     redeemer,
//     input_utxo,
//     tx,
//   )
// }
