name: Script CI Tests

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: aiken-lang/setup-aiken@v1
        with:
          version: v1.1.0
      - run: aiken fmt --check
      - run: aiken check -D
      - run: aiken docs
